version: "3"
services:
  web:
    build: .
    container_name: web
    volumes:
      - .:/src
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    # If you use M1 or M2 Mac, uncommnet the below line
      # platform: linux/x86_64
    image: mysql:5.7
    container_name: db
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: <your-db-name>
      MYSQL_USER: <username>
      MYSQL_PASSWORD: <password>
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "admin", "-padmin"]
      timeout: 20s
      retries: 3
volumes:
  mysql:
